import type { Instrument, LikertSection, TextSection } from "@/lib/instrument";
import type { AnswerMap } from "@/lib/steps";

/**
 * Prompt builders for the four AI features (PRD §7). The instrument's own
 * embedded rules are baked into every system prompt: summaries of 1-2
 * sentences, only the respondent's language, no interpretation or new
 * information, and everything user-facing is labeled AI-generated by the UI.
 */

const GLOBAL_RULES = `Rules that always apply:
- Use ONLY the respondent's own language, terms, and facts. Never add interpretation, outside knowledge, or new information.
- If an answer is missing or marked "don't know", treat it as unknown - never invent content for it.
- Write plainly for health-program staff, not technologists.`;

export function answerText(
  answers: AnswerMap,
  id: string
): { state: "answered"; text: string } | { state: "idk" } | { state: "empty" } {
  const v = answers[id];
  if (v?.idk) return { state: "idk" };
  const t = v?.text?.trim();
  if (t) return { state: "answered", text: t };
  return { state: "empty" };
}

function qaBlock(section: TextSection, answers: AnswerMap): string {
  return section.questions
    .map((q) => {
      const a = answerText(answers, q.id);
      const body =
        a.state === "answered"
          ? a.text
          : a.state === "idk"
            ? "[respondent marked: I don't know]"
            : "[not answered]";
      return `${q.id} — ${q.prompt}\n${body}`;
    })
    .join("\n\n");
}

// ------------------------------------------------------------------ summary

export const SUMMARY_SCHEMA = {
  type: "object",
  properties: { summary: { type: "string" } },
  required: ["summary"],
  additionalProperties: false,
};

export function summaryPrompts(instrument: Instrument, answers: AnswerMap) {
  const sectionA = instrument.sections.find(
    (s): s is TextSection => s.type === "text" && s.id === "A"
  )!;
  return {
    system: `You summarize the problem a health-sector team described in an AI-readiness assessment, so they can confirm the tool understood them.
${GLOBAL_RULES}
- Output exactly 1-2 sentences describing the use case and the need it addresses.`,
    user: `The team's Section A answers:\n\n${qaBlock(sectionA, answers)}\n\nWrite the 1-2 sentence problem summary.`,
  };
}

// -------------------------------------------------------------------- recap

export const RECAP_SCHEMA = {
  type: "object",
  properties: { recap: { type: "string" } },
  required: ["recap"],
  additionalProperties: false,
};

export function recapPrompts(section: TextSection, answers: AnswerMap) {
  return {
    system: `You write a one-breath "quick check" recap of what a team just wrote in one section of an AI-readiness assessment, so they can confirm it before continuing.
${GLOBAL_RULES}
- Output exactly 1-2 sentences, addressed to the team ("You described...").`,
    user: `Section "${section.title}" answers:\n\n${qaBlock(section, answers)}\n\nWrite the 1-2 sentence recap.`,
  };
}

// ---------------------------------------------------------------- judgment

export const JUDGMENT_SCHEMA = {
  type: "object",
  properties: {
    elements: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string",
            enum: ["data_readiness", "safety", "country_readiness", "use_case_readiness"],
          },
          level: { type: "string", enum: ["red", "amber", "green"] },
          reasoning: { type: "string" },
          drivers: {
            type: "array",
            items: {
              type: "object",
              properties: {
                qid: { type: "string" },
                direction: { type: "string", enum: ["strength", "gap"] },
              },
              required: ["qid", "direction"],
              additionalProperties: false,
            },
          },
          confidence: { type: "string", enum: ["high", "medium", "low"] },
        },
        required: ["id", "level", "reasoning", "drivers", "confidence"],
        additionalProperties: false,
      },
    },
    overall_note: { type: "string" },
  },
  required: ["elements", "overall_note"],
  additionalProperties: false,
};

export type Judgment = {
  elements: {
    id: "data_readiness" | "safety" | "country_readiness" | "use_case_readiness";
    level: "red" | "amber" | "green";
    reasoning: string;
    drivers: { qid: string; direction: "strength" | "gap" }[];
    confidence: "high" | "medium" | "low";
  }[];
  overall_note: string;
  fallback?: boolean;
};

const USE_CASE_RUBRIC = `Judge use_case_readiness against five criteria (PRD Appendix A), each on the evidence in Sections A/B only:
1. Specificity - one defined input, one defined output, a named user of the output (A1, B2, B3).
2. AI-appropriateness - a stated reason AI beats a rule-based tool (A3). A problem rules could solve caps this element at amber and the reasoning must say so.
3. Measurable success - concrete metrics with baselines; ROI thinking (A5, A6).
4. Workflow clarity & human oversight - current process, actors, stage inputs/outputs described; a human review point defined (B1-B3).
5. Constraint awareness - realistic regulatory/budget/institutional constraints identified (A4).`;

export function judgmentPrompts(input: {
  summary: string | null;
  sectionsAB: string;
  ratingBlocks: string;
  aggregates: string;
  c1Label: string | null;
}) {
  return {
    system: `You are the readiness judge of an AI use-case assessment for health-sector teams. You rate four elements - data_readiness, safety, country_readiness (each from the team's structured ratings) and use_case_readiness (from their written answers) - as red (Absent), amber (Partially Meets the Criteria), or green (Fully Meets the Criteria).
${GLOBAL_RULES}
Hard requirements:
- Ground every rating strictly in the provided ratings and answers. The rating levels must faithfully reflect the team's own ratings; do not be more generous or harsher than their answers support.
- For each element, cite at least 2 of the provided question IDs as drivers (the answers that most drove the rating).
- reasoning: at most 120 words per element, plain language, using the team's vocabulary. Name the concrete strengths and gaps.
- confidence: "low" whenever the team lacks information (many "don't know"/unanswered); otherwise reflect how clearly the evidence points one way.
- overall_note: 1-2 sentences on the overall picture and the single most important next step.
${USE_CASE_RUBRIC}`,
    user: `PROBLEM SUMMARY (confirmed by the team${input.c1Label ? `, rated "${input.c1Label}"` : ""}):
${input.summary ?? "[none]"}

SECTION A/B ANSWERS:
${input.sectionsAB}

READINESS RATINGS:
${input.ratingBlocks}

PER-ELEMENT RATING AGGREGATES:
${input.aggregates}

Rate the four elements.`,
  };
}

// --------------------------------------------------------------- follow-ups

export const FOLLOWUPS_SCHEMA = {
  type: "object",
  properties: {
    todos: {
      type: "array",
      items: {
        type: "object",
        properties: {
          qid: { type: ["string", "null"] },
          action: { type: "string" },
          why: { type: "string" },
        },
        required: ["qid", "action", "why"],
        additionalProperties: false,
      },
    },
  },
  required: ["todos"],
  additionalProperties: false,
};

export type Followups = {
  todos: { qid: string | null; action: string; why: string }[];
  fallback?: boolean;
};

export function followupsPrompts(gaps: string) {
  return {
    system: `You turn the gaps in a team's AI-readiness assessment into a short, concrete "things to find out" list.
${GLOBAL_RULES}
Hard requirements:
- At most 8 items, ordered by importance.
- Every item must trace to one specific gap provided below (set its qid). No generic advice.
- action: one imperative sentence a team member could act on this week ("Ask the data management team whether duplicate checks have ever been run on the registry").
- why: one short clause on why it matters for readiness.
- If the answers name roles or teams, direct the action to them.`,
    user: `The team's gaps:\n\n${gaps}\n\nWrite the follow-up list.`,
  };
}

// ------------------------------------------------------------ shared context

export function buildSectionsAB(instrument: Instrument, answers: AnswerMap): string {
  return instrument.sections
    .filter((s): s is TextSection => s.type === "text")
    .map((s) => qaBlock(s, answers))
    .join("\n\n");
}

export function buildRatingBlocks(
  sections: LikertSection[],
  answers: AnswerMap,
  scaleLabel: (r: number) => string
): string {
  return sections
    .map((s) => {
      const rows = s.items
        .map((it) => {
          const v = answers[it.id];
          const val = v?.na
            ? "N/A"
            : v?.idk
              ? "I don't know"
              : typeof v?.rating === "number"
                ? scaleLabel(v.rating)
                : "[not rated]";
          return `${it.id} — ${it.statement}\n   rated: ${val}`;
        })
        .join("\n");
      return `${s.id} · ${s.title} ("${s.question}")\n${rows}`;
    })
    .join("\n\n");
}
